### ISSUE TITLE
Maven dependency of android-rest-additions v2.2.0 is incorrect

### ISSUE THREAD

**Issue by dailystudio** [darko1002001/android-rest-client#5]
Hi darko,

I used anroid-rest-client v1.3.0 before in my own projects with Eclipse build. Everything was all right. Now I am switching to use android-rest-client library in Android Studio through Gradle build. I added the following dependency in build.gradle:
    compile 'com.aranea-apps.android.libs:android-rest:2.2.0'
    compile 'com.aranea-apps.android.libs:android-rest-additions:2.2.0'
But it always reported that 
    Could not find com.aranea-apps.android.libs:android-rest:2.2.0.0.

I checked the pom of android-rest-additions artifact under following URL:
https://oss.sonatype.org/content/repositories/releases/com/aranea-apps/android/libs/android-rest-additions/2.2.0/android-rest-additions-2.2.0.pom
and I think the part below may be incorrect:
\<dependency\>
\<groupId>com.aranea-apps.android.libs\</groupId\>
\<artifactId\>android-rest\</artifactId\>
\<version\>2.2.0.0\</version\>
\<scope\>compile\</scope\>
\</dependency\>
It will tell Gradle to download com.aranea-apps.android.libs:android-rest:2.2.0.0, but there is only com.aranea-apps.android.libs:android-rest:2.2.0.

Could you please to confirm if there is some problem with that pom file or I have some misunderstanding about this issue?

Best regards,
Nan YE

**Comment by darko1002001** [comment]
Yes the version at this time is 2.2.0. I have migrated the project to gradle so the pom is not valid anymore. I have pushed the edit to the build gradle. 

Basically the release version is specified in the maven push script and the version wasn't reflected properly in the main build file.

**Comment by darko1002001** [comment]
1b57871eb9140166ccd8af07c45215b80ee92f66
