### ISSUE TITLE
New GitHub release

### ISSUE THREAD

**Issue by jitpack-io** [darko1002001/android-rest-client#6]
Hi!

We're seeing users trying to install android-rest-client via JitPack.io:
https://jitpack.io/#darko1002001/android-rest-client/0c2284084b
It works great but would be nice to have some new GitHub releases. Then we'd be able to use a version number instead of a commit id.

**Comment by darko1002001** [comment]
There are releases on maven central.

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.aranea-apps.android.libs%22%20AND%20a%3A%22android-rest%22

and for the additions

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.aranea-apps.android.libs%22%20AND%20a%3A%22android-rest-additions%22

**Comment by jitpack-io** [comment]
Oh ok. In any case a GitHub release could be nice as well:)
